#
#AltCheck v1.8 by uz_masa3
#Translate by Google Translate.
#

yml: "%altcheck%/data.yml"

#en: When the same accounts as IP exceeds this value, the account will kick.
#ja: 同じIPでこの数値を上回る数のアカウントで入った場合、そのIPで入ってきたアカウントは全員Kickされます。
maxAlt: 2

#en: When exceeds maxAlt value, kick with this message.
#ja: maxAltを上回る数のアカウントで入ってきた場合にKickするメッセージ
kickMessage: "You can't use alternate accounts."

#en: When join, they aren't check alt accounts.
#ja: このUUIDが参加した時はmaxAltを上回った場合でもKickされません。
IgnoreCheckAlt:
- 069a79f4-44e9-4726-a5be-fca90e38aaf5
- af74a02d-19cb-445b-b07f-6866a861f783

CountryFilter: false
CountryKickMessage: "Your country is not whitelisted!!"
WhitelistedCountry:
  - Japan

#en: When join, they aren't check country.
#ja: このUUIDが参加した時はCountryFilterを無視します。
IgnoreCountryFilter:
- 069a79f4-44e9-4726-a5be-fca90e38aaf5
- af74a02d-19cb-445b-b07f-6866a861f783

messages:
  notfound: "&7Data not found."
  checkHeader: "&7============&c%ip%&7============"
  reload: "&7Reload complete."
  nopermission: "&cYou don't have permission."
  save: "&aSuccessfully save settings."
  enternumber: "&cPlease enter a number."

#DO NOT TOUCH!!!!
configVersion: 6
